services:
    postgres:
      image: postgres:latest
      container_name: loopin-api-db
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345678
        POSTGRES_DB: loopin-api
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: